### PR TITLE
Change new playlist_item default title to include structure info

### PR DESCRIPTION
**Pull request by bkeese**
Default playlist_item title will now include structure labels, if available. Default title will have the form:

MediaObject.title - MasterFile.title (or filename) - Structure Level 1 label - ... - Structure Span label

### CODE REVIEW

**Review by cjcolvar — COMMENTED** [review]
The parent lookup seems pretty brittle but if that is what works :+1:.  It might be nice to extract this to a method so it can be easier to port to the mejs4 player.

@adamjarling do you have any thoughts?

**Comment by bkeese** [comment]
Yeah, the html for the structure stuff is Ugly. But, at least it is consistent.

**Comment by cjcolvar** [comment]
@adamjarling I'm going to go ahead and merge this because we need to deploy it here at IU soon, but I still value your feedback as this will need to be ported to the mejs 4 player.

**Comment by cjcolvar** [comment]
Fixes https://github.com/avalonmediasystem/avalon/issues/982.

**Comment by adamjarling** [comment]
@bkeese @cjcolvar Made a few quick comments, for clarification.  Can we talk through this for a few minutes today?

**Pull request merged**
